---
- name: "Jinja template testing"
  hosts: all
  vars:
     url: "http://example.com/users/foo/resources/bar"
  
  tasks:
  - shell: cat /home/ubuntu/multidoc-file.yaml
    register: result
  - debug:
      msg: '{{ item }}'
      #loop: '{{ result.stdout | from_yaml_all | list }}'
    loop: '{{ result.stdout | from_yaml |list }}'
  - debug:
        msg: "matched pattern 1"
      when: url is match("http://example.com/users/.*/resources/.*")

  - debug:
        msg: "matched pattern 2"
      when: url is search("/users/.*/resources/.*")

  - debug:
        msg: "matched pattern 3"
      when: url is search("/users/")

  - debug:
        msg: "matched pattern 4"
      when: url is regex("example.com/\w+/foo")
