---
- name: "Jinja template testing"
  hosts: all
  tasks:
        - shell: cat /home/ubuntu/file.json
          register: result

        - set_fact:
             myvar: "{{ result.stdout | from_json }}"      
