---
- name: "Register in loop"
  hosts: all
  tasks:
          - name: count our fruit
            debug:
                    msg: "{{ item }} with index {{ my_idx }}"
            loop:
                - apple
                - banana
                - pear
            loop_control:
                 index_var: my_idx
