---
- name: "When condition testing"
  hosts: all
  tasks:
         - name: "Creating file on debain flavour server"
           file: 
                path: /home/ubuntu/ubuntu_dir
                state: directory
                mode: '0777'
           #when: ansible_facts['os_family'] == "debian"
           when: ansible_distribution == "Ubuntu"
        
         - name: "Creating directory in redhat flavour servers"
           file:
                    path: /home/ec2-user/centos_dir
                    state: directory
                    mode: '0777'
           #when: ansible_facts['os_family'] == "centos"
           when: ansible_distribution == 'Amazon' or ansible_distribution == 'Red Hat Enterprise Linux'


         - name: "Crating a file in Amazon Linux"
           file:
                    path: /home/ec2-user/centos_dir/amazon.txt
                    state: touch
                    mode: '0777'
           when: ansible_distribution == 'Amazon' or ansible_distribution == 'Red Hat Enterprise Linux'

         - name: "Creating file in ubuntu_dir directory"
           file:
                path: /home/ubuntu/ubuntu_dir/ubuntu.txt
                state: touch
                mode: '0777'
           when: 
                - ansible_distribution == "Ubuntu"  
                - ansible_facts['distribution_major_version'] < "20"
