---

dependencies: []

galaxy_info:

  company: 'DebOps'
  author: 'Reto Gantenbein'
  description: 'Manage Kibana analytics and visualization platform'
  license: 'GPL-3.0'
  min_ansible_version: '2.0.0'

  platforms:

    - name: Debian
      versions:
        - jessie

  galaxy_tags:
    - kibana
    - elasticsearch
    - debops
